on:
  push:
    tags:
      - 'v*'

name: Build and Release

jobs:

  release:
    name: 'Create Release from Tag'
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false

  build:
    name: 'Build & Upload ${{ matrix.arch }} DLL'
    runs-on: windows-latest
    needs: release
    strategy:
      matrix:
        arch: ['amd64', '386']

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Setup Golang Environment'
        uses: actions/setup-go@v2
        with:
          go-version: '^1.14'

      - name: 'Build ${{ matrix.OSes }}-${{ matrix.arch }}'
        run: |
          set GOARCH=${{ matrix.arch }}
          set CGO_ENABLED=1
          go build -trimpath -ldflags="-s -w -buildid=" -buildmode=c-shared -o dummy_${{ matrix.arch }}.dll

      - name: 'Upload Release Assets'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dummy_${{ matrix.arch }}.dll
          asset_name: dummy_${{ matrix.arch }}.dll
          asset_content_type: application/octet-stream

